// <auto-generated />
namespace EntityFramework_DemoProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Event_club : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Event_club));
        
        string IMigrationMetadata.Id
        {
            get { return "202302230620083_Event_club"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
